openapi: 3.0.0
info:
  title: Micro-like Collaborative Whiteboard API
  description: API for a collaborative whiteboard application similar to Micro-like
  version: 1.0.0
path:
  /boards:
    get:
      $ref: "./endpoints/boards.yaml#/getAllBoards"

    post:
      $ref: "./endpoints/boards.yaml#/createBoard"

  /boards/{boardId}:
    delete:
      $ref: "./endpoints/boards.yaml#/deleteBoard"